theme: minima
title: Frederik Glitzner
author: 
  name: Frederik Glitzner
  email: f.LASTNAME.1@research.gla.ac.uk
description: >
  Personal Homepage
show_excerpts: true
minima:
  skin: dark
  plugins:
    - jekyll-feed
  social_links:
    - { platform: github,         user_url: "https://github.com/glitznerf" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/frederik-g" }
    #- { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=" }
